application: glogdemo
version: beta
runtime: go
api_version: go1

handlers:

- url: /static
  static_dir: static
  application_readable: true

- url: /css
  static_dir: static/css
  application_readable: true

- url: /js
  static_dir: static/js
  application_readable: true

- url: /fonts
  static_dir: static/fonts
  application_readable: true

- url: /.*
  script: _go_app
  login: admin